name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          
      - name: Restore dependencies
        run: dotnet restore Wolfteam.Server.Tests
        
      - name: Build
        run: dotnet build Wolfteam.Server.Tests --no-restore
      
      - name: Test
        run: dotnet test Wolfteam.Server.Tests/Wolfteam.Server.Tests.csproj --no-build --verbosity normal
